Update NSTALL.md and add `test_env.py` script
facebookresearch/ssvp_slt pull request #7
Opened 2024-10-23 18:24 UTC by JooZef315

### Changes
1. Added instructions for setting up Python dependencies using `pip` and `conda` in the INSTALL.md.
2. Created a script (`test_env.py`) that:
   - Checks Python version compatibility.
   - Reports if the environment is ready for development.
   
### Testing Instructions
1. Follow the steps in the INSTALL.mdto set up the environment.
2. Run the script using `python test_env.py`.
3. Ensure the output confirms that the environment is set up correctly.

### Related Issues
- Resolves #6: Add instructions for setting up the Python environment and provide a script to test the setup

2024-10-27 12:05 UTC, antoine-tran commented on INSTALL.md
> +conda create --name ssvp_slt python=3.10 cmake ipython
Why do we need ipython here ?

2024-10-28 10:08 UTC, JooZef315 commented on INSTALL.md
> +conda create --name ssvp_slt python=3.10 cmake ipython
Done. removed it. thanks

2024-11-04 17:28 UTC, heffernankevin commented on INSTALL.md
> +- visual studio visual studio (2022/2019/2017) build tools
Perhaps this was required for Windows only? (nit: `visual studio` is repeated twice)

2024-11-04 17:40 UTC, heffernankevin commented on INSTALL.md
> +python -m pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu118
You can remove L16 since `torch` and `torchvision` are also defined there. Let's just specify one version of each library.

2024-11-04 17:41 UTC, heffernankevin commented on INSTALL.md
> +#### 7. Test your env
nit: this should be number `8` not `7`

2024-11-04 17:43 UTC, heffernankevin commented on test_env.py
> +  # Consider using a runtime with GPU acceleration in Colab.
You can remove this comment.

2024-11-04 17:44 UTC, heffernankevin commented on test_env.py
> +import torch
Ideally I would create a directory called `tests` and put this there

2024-11-04 17:45 UTC, heffernankevin requested changes

2024-11-04 17:45 UTC, heffernankevin commented on INSTALL.md
> +you can excute `test_env.py` python script to check if the dependencies are installed
nit: `excute` -> `execute`

2024-11-04 21:00 UTC, heffernankevin approved these changes
LGTM!

2024-11-04 21:05 UTC, heffernankevin commented on tests/test_env.py
> +# References:
Can you remove L6 -> L10

2024-11-06 14:05 UTC, merged